// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: imooc.proto

package go_micro_service_imooc

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	api "github.com/micro/go-micro/v2/api"
	client "github.com/micro/go-micro/v2/client"
	server "github.com/micro/go-micro/v2/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ api.Endpoint
var _ context.Context
var _ client.Option
var _ server.Option

// Api Endpoints for Roach service

func NewRoachEndpoints() []*api.Endpoint {
	return []*api.Endpoint{}
}

// Client API for Roach service

type RoachService interface {
	SayHello(ctx context.Context, in *SayRequest, opts ...client.CallOption) (*SayResponse, error)
}

type roachService struct {
	c    client.Client
	name string
}

func NewRoachService(name string, c client.Client) RoachService {
	return &roachService{
		c:    c,
		name: name,
	}
}

func (c *roachService) SayHello(ctx context.Context, in *SayRequest, opts ...client.CallOption) (*SayResponse, error) {
	req := c.c.NewRequest(c.name, "Roach.SayHello", in)
	out := new(SayResponse)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Roach service

type RoachHandler interface {
	SayHello(context.Context, *SayRequest, *SayResponse) error
}

func RegisterRoachHandler(s server.Server, hdlr RoachHandler, opts ...server.HandlerOption) error {
	type roach interface {
		SayHello(ctx context.Context, in *SayRequest, out *SayResponse) error
	}
	type Roach struct {
		roach
	}
	h := &roachHandler{hdlr}
	return s.Handle(s.NewHandler(&Roach{h}, opts...))
}

type roachHandler struct {
	RoachHandler
}

func (h *roachHandler) SayHello(ctx context.Context, in *SayRequest, out *SayResponse) error {
	return h.RoachHandler.SayHello(ctx, in, out)
}
